import type {Metadata} from "next";
import {Inter} from 'next/font/google';
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {Navigation} from "@/components/navigation";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.className} suppressHydrationWarning>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <Navigation />
        <main className="container mx-auto px-4 py-8">
          {children}
        </main>
      </ThemeProvider>
      </body>
      </html>
  );
}
